---
main:
  width: 800
  height: 800
  output: /home/example.jpg
  renderThreads: 4
camra:
  position: 0,0,0
  sample: 16
lights:
- name: light1
  kind: SimplePointLight
  args:
    position: 10000000,10000000,10000000
    color: 255,255,255,255
    ls: 1.0
objects:
- name: WhiteSphere
  kind: Sphere
  args:
    center: 0,120,0
    radius: 120
  material:
    kind: SpecularPhong
    args:
      ks: 0.3
      kd: 0.5
      exp: 3
      color: 255, 255, 255, 255
- name: bottomPlane
  kind: Rect
  args:
    width: 800
    length: 800
    position: 0,0,0
    localX: 1,0,1
    localY: 0,1,0
    localZ: -1,0,1
  material:
    kind: SV_Matte
    args:
      size: 50
      color1: 255, 255, 255, 255
      color2: 0, 0, 0, 255